---
- name: IP3 yolo Playbook
  hosts: webservers
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Cloning the Full-stack Web App from GitHub
      git:
        repo: https://github.com/Vinge1718/yolo
        dest: /home/vagrant
        version: master

    - name: Install Node.js and npm
      apt:
        name: ["nodejs", "npm"]
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Allow incoming traffic on port 5000 (frontend)
      ufw:
        rule: allow
        port: 5000

    - name: Allow incoming traffic on port 3000 (backend)
      ufw:
        rule: allow
        port: 3000

    - name: Enable ufw firewall
      ufw:
        state: enabled

    - name: Start MongoDB service
      service:
        name: mongod
        state: started

    - name: Install npm dependencies for frontend
      command: npm install
      args:
        chdir: /home/vagrant/yolo/client

    - name: Install npm dependencies for backend
      command: npm install
      args:
        chdir: /home/vagrant/yolo/backend

    - name: Start frontend server
      command: npm start
      args:
        chdir: /home/vagrant/yolo/client

    - name: Start backend server
      command: npm start
      args:
        chdir: /home/vagrant/yolo/backend

    - name: Add MongoDB user
      mongo_user:
        login_user: admin
        login_password: password
        user: bob
        password: 12345
        roles: readWrite

    - name: Create MongoDB database
      mongo_db:
        login_user: bob
        login_password: 12345
        name: appdb

